# Generated by Django 4.2.2 on 2023-12-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='games',
            field=models.ManyToManyField(related_name='applicants', to='app1.game'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(upload_to='applicant_photos/'),
        ),
    ]
