# Generated by Django 4.2.2 on 2023-12-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
